apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prestashop-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: prestashop-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: prestashop-secret
                  key: MYSQL_USER
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prestashop-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prestashop
spec:
  selector:
    matchLabels:
      app: prestashop
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prestashop
    spec:
      containers:
        - image: prestashop/prestashop
          name: prestashop
          env:
            - name: DB_SERVER
              value: mysql
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: prestashop-secret
                  key: MYSQL_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: prestashop-secret
                  key: MYSQL_USER
            - name: DB_PASSWD
              valueFrom:
                secretKeyRef:
                  name: prestashop-secret
                  key: MYSQL_PASSWORD
            - name: PS_SHOP_NAME
              valueFrom:
                configMapKeyRef:
                  name: prestashop-configmap
                  key: SHOP_NAME
          ports:
            - containerPort: 80
              name: prestashop
          volumeMounts:
            - name: prestashop-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: prestashop-persistent-storage
          persistentVolumeClaim:
            claimName: prestashop-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: prestashop
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: prestashop
